### ISSUE TITLE
Typing error in the documentation of the preg_match function (https://www.php.net/manual/fr/function.preg-match.php)

### ISSUE THREAD

**Issue by SIKessEm** [php/doc-fr#102]
### The word "survient." is repeated twice in the documentation of the return value.

This is not a serious enough error, but I still wanted to point it out so as not to confuse some people.

**The doc fr:**
![doc-fr](https://user-images.githubusercontent.com/62618356/134037492-08c9f174-fc1b-44d8-83f0-6a368d339c79.png)

**The doc en:**
![doc-en](https://user-images.githubusercontent.com/62618356/134037478-016f7111-c748-424b-b2c6-fe3b83ef2f46.png)

**Comment by adoy** [comment]
Documentation was corrected. Thanks for your help.
