### ISSUE TITLE
PHP et VSC

### ISSUE THREAD

**Issue by marekredon** [php/doc-fr#105]
From manual page: https://php.net/faq.misc
---
Bonjour à tous, 
Je n'arrive pas à mettre en route  l'extension PHP server sur VSC. (le plugin s'est bien installé)
J'ai ce message :

![](https://cdn.discordapp.com/attachments/752234373696192643/893520438796374077/unknown.png)

En refermant VSC et en l'ouvrant, j'ai eu ça :

![](https://cdn.discordapp.com/attachments/752234373696192643/893522566692614174/unknown.png)

qui mène à ça

![](https://cdn.discordapp.com/attachments/752234373696192643/893522663392313414/unknown.png)

On m'a dit d'aller voir https://www.php.net/downloads.php
et de télécharger un des lien proposé ici :

![](https://cdn.discordapp.com/attachments/752234373696192643/893524097806532618/unknown.png)

J'en ai téléchargé 2 , mais lorsque je clique sur n'importe quel .exe, j'ai ça :

![](https://cdn.discordapp.com/attachments/752234373696192643/893528783032823858/unknown.png)

QQn a une solution ?

**Comment by bborrel** [comment]
@marekredon Ici c'est le dépôt pour la traduction française de la documentation PHP, et ce n'est donc pas la place pour poser ce genre de question. Réfère toi plutôt à :
- pour l'installation de PHP sur Windows : https://www.php.net/manual/fr/install.windows.php
- pour l'usage de PHP avec VSCode : https://code.visualstudio.com/docs/languages/php 

Ceci dit, pour répondre directement à tes questions :
1. La balise d'ouverture d'un script PHP est `<?php`, et non `< ?php` comme tu l'as écris dans ton fichier `index.php`.
2. Double-cliquer sur `php.exe` ne te donnera rien. PHP doit être invoqué obligatoirement avec le chemin d'un script en paramètre. Ex: `php.exe C:\CheminVers\index.php`
