### ISSUE TITLE
php8.3 The following packages have unmet dependencies:

### ISSUE THREAD

**Issue by aragon5956** [php/doc-fr#1324]
hello ,
I pose this problem there because I have trouble subscribing to php.net mails , and I think that no one will answer .I have this error when I want to install php8.3 for all extensions, could you help me ?
 `sudo apt install php8.3-*
....
The following packages have unmet dependencies:
 php8.3-apcu : Conflicts: php-yac
 php8.3-gmagick : Conflicts: php-imagick
                  Recommends: ttf-dejavu-core but it is not installable
 php8.3-yac : Conflicts: php-apcu
E: Unable to correct problems, you have held broken packages`

and and by tabulating I get this : 
`alexandre@ubuntu:/var/www/SiteWebUniverseUtility$ sudo apt install tt
tt-rss                      ttf-engadget                ttf-summersby               ttfautohint                 ttv                         ttygif                      
ttf-ancient-fonts           ttf-mscorefonts-installer   ttf-tagbanwa                tth                         tty-clock                   ttyload                     
ttf-ancient-fonts-symbola   ttf-radisnoir               ttf-xfree86-nonfree         tth-common                  tty-share                   ttylog                      
ttf-anonymous-pro           ttf-sjfonts                 ttf-xfree86-nonfree-syriac  tthsum                      tty-solitaire               ttyrec                      
ttf-bitstream-vera          ttf-staypuft                ttf2ufm `

**Comment by devnexen** [comment]
Maybe you need to do `apt update` first or maybe you are using debian unstable in which this type of issue occurs from time to time. Anyhow, this is not the place to ask technical questions, this is not quite related to php but debian package part.

**Comment by aragon5956** [comment]
no ,
`alexandre@ubuntu:/var/www/SiteWebUniverseUtility$ sudo apt update -y 
Get:1 http://repo.mysql.com/apt/ubuntu jammy InRelease [25.1 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                                                                                                    
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]                                                                                                           
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]                                                                                                                       
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease                                                                                                                                    
Get:6 http://repo.mysql.com/apt/ubuntu jammy/mysql-8.4-lts Sources [968 B]                                                       
Get:8 http://repo.mysql.com/apt/ubuntu jammy/mysql-apt-config amd64 Packages [566 B]                              
Hit:9 https://ppa.launchpadcontent.net/cappelikan/ppa/ubuntu jammy InRelease                        
Hit:10 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease                                
Get:11 http://repo.mysql.com/apt/ubuntu jammy/mysql-8.4-lts amd64 Packages [18.9 kB]                       
Hit:12 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy InRelease                   
Get:13 http://repo.mysql.com/apt/ubuntu jammy/mysql-tools amd64 Packages [4161 B]           
Hit:7 https://packagecloud.io/crowdsec/crowdsec/any any InRelease
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1987 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1112 kB]
Fetched 3406 kB in 5s (722 kB/s)                           
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
alexandre@ubuntu:/var/www/SiteWebUniverseUtility$ sudo apt install php8.3-*
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'php8.3-xmlwriter' for glob 'php8.3-*'
Note, selecting 'php8.3-apcu' for glob 'php8.3-*'
Note, selecting 'php8.3-uploadprogress' for glob 'php8.3-*'
Note, selecting 'php8.3-xml' for glob 'php8.3-*'
Note, selecting 'php8.3-xsl' for glob 'php8.3-*'
Note, selecting 'php8.3-enchant' for glob 'php8.3-*'
Note, selecting 'php8.3-yac' for glob 'php8.3-*'
Note, selecting 'php8.3-zip' for glob 'php8.3-*'
Note, selecting 'php8.3-zmq' for glob 'php8.3-*'
Note, selecting 'php8.3-mysqlnd' for glob 'php8.3-*'
Note, selecting 'php8.3-pdo-pgsql' for glob 'php8.3-*'
Note, selecting 'php8.3-calendar' for glob 'php8.3-*'
Note, selecting 'php8.3-tokenizer' for glob 'php8.3-*'
Note, selecting 'php8.3-redis' for glob 'php8.3-*'
Note, selecting 'php8.3-phpdbg' for glob 'php8.3-*'
Note, selecting 'php8.3-maxminddb' for glob 'php8.3-*'
Note, selecting 'php8.3-grpc' for glob 'php8.3-*'
Note, selecting 'php8.3-mysqli' for glob 'php8.3-*'
Note, selecting 'php8.3-msgpack' for glob 'php8.3-*'
Note, selecting 'php8.3-gmagick' for glob 'php8.3-*'
Note, selecting 'php8.3-simplexml' for glob 'php8.3-*'
Note, selecting 'php8.3-inotify' for glob 'php8.3-*'
Note, selecting 'php8.3-interbase' for glob 'php8.3-*'
Note, selecting 'php8.3-memcache' for glob 'php8.3-*'
Note, selecting 'php8.3-mbstring' for glob 'php8.3-*'
Note, selecting 'php8.3-common' for glob 'php8.3-*'
Note, selecting 'php8.3-sybase' for glob 'php8.3-*'
Note, selecting 'php8.3-fileinfo' for glob 'php8.3-*'
Note, selecting 'php8.3-pdo-sqlite' for glob 'php8.3-*'
Note, selecting 'php8.3-phalcon5' for glob 'php8.3-*'
Note, selecting 'php8.3-decimal' for glob 'php8.3-*'
Note, selecting 'php8.3-pdo-mysql' for glob 'php8.3-*'
Note, selecting 'php8.3-libvirt-php' for glob 'php8.3-*'
Note, selecting 'php8.3-mcrypt' for glob 'php8.3-*'
Note, selecting 'php8.3-readline' for glob 'php8.3-*'
Note, selecting 'php8.3-snmp' for glob 'php8.3-*'
Note, selecting 'php8.3-soap' for glob 'php8.3-*'
Note, selecting 'php8.3-solr' for glob 'php8.3-*'
Note, selecting 'php8.3-opcache' for glob 'php8.3-*'
Note, selecting 'php8.3-imagick' for glob 'php8.3-*'
Note, selecting 'php8.3-http' for glob 'php8.3-*'
Note, selecting 'php8.3-igbinary' for glob 'php8.3-*'
Note, selecting 'php8.3-yaml' for glob 'php8.3-*'
Note, selecting 'php8.3-ssh2' for glob 'php8.3-*'
Note, selecting 'php8.3-xdebug' for glob 'php8.3-*'
Note, selecting 'php8.3-oauth' for glob 'php8.3-*'
Note, selecting 'php8.3-smbclient' for glob 'php8.3-*'
Note, selecting 'php8.3-curl' for glob 'php8.3-*'
Note, selecting 'php8.3-mailparse' for glob 'php8.3-*'
Note, selecting 'php8.3-raphf' for glob 'php8.3-*'
Note, selecting 'php8.3-tidy' for glob 'php8.3-*'
Note, selecting 'php8.3-imap' for glob 'php8.3-*'
Note, selecting 'php8.3-pspell' for glob 'php8.3-*'
Note, selecting 'php8.3-intl' for glob 'php8.3-*'
Note, selecting 'php8.3-ctype' for glob 'php8.3-*'
Note, selecting 'php8.3-pgsql' for glob 'php8.3-*'
Note, selecting 'php8.3-gnupg' for glob 'php8.3-*'
Note, selecting 'php8.3-odbc' for glob 'php8.3-*'
Note, selecting 'php8.3-iconv' for glob 'php8.3-*'
Note, selecting 'php8.3-pdo-odbc' for glob 'php8.3-*'
Note, selecting 'php8.3-xhprof' for glob 'php8.3-*'
Note, selecting 'php8.3-zstd' for glob 'php8.3-*'
Note, selecting 'php8.3-mongodb' for glob 'php8.3-*'
Note, selecting 'php8.3-swoole' for glob 'php8.3-*'
Note, selecting 'php8.3-tideways' for glob 'php8.3-*'
Note, selecting 'php8.3-sockets' for glob 'php8.3-*'
Note, selecting 'php8.3-memcached' for glob 'php8.3-*'
Note, selecting 'php8.3-uopz' for glob 'php8.3-*'
Note, selecting 'php8.3-sysvmsg' for glob 'php8.3-*'
Note, selecting 'php8.3-mysql' for glob 'php8.3-*'
Note, selecting 'php8.3-json' for glob 'php8.3-*'
Note, selecting 'php8.3-pcov' for glob 'php8.3-*'
Note, selecting 'php8.3-uuid' for glob 'php8.3-*'
Note, selecting 'php8.3-sysvsem' for glob 'php8.3-*'
Note, selecting 'php8.3-sysvshm' for glob 'php8.3-*'
Note, selecting 'php8.3-phar' for glob 'php8.3-*'
Note, selecting 'php8.3-bcmath' for glob 'php8.3-*'
Note, selecting 'php8.3-shmop' for glob 'php8.3-*'
Note, selecting 'php8.3-gettext' for glob 'php8.3-*'
Note, selecting 'php8.3-sqlite3' for glob 'php8.3-*'
Note, selecting 'php8.3-pdo-dblib' for glob 'php8.3-*'
Note, selecting 'php8.3-excimer' for glob 'php8.3-*'
Note, selecting 'php8.3-protobuf' for glob 'php8.3-*'
Note, selecting 'php8.3-exif' for glob 'php8.3-*'
Note, selecting 'php8.3-gearman' for glob 'php8.3-*'
Note, selecting 'php8.3-xmlreader' for glob 'php8.3-*'
Note, selecting 'php8.3-vips' for glob 'php8.3-*'
Note, selecting 'php8.3-pinba' for glob 'php8.3-*'
Note, selecting 'php8.3-pdo-firebird' for glob 'php8.3-*'
Note, selecting 'php8.3-ast' for glob 'php8.3-*'
Note, selecting 'php8.3-bz2' for glob 'php8.3-*'
Note, selecting 'php8.3-cgi' for glob 'php8.3-*'
Note, selecting 'php8.3-cli' for glob 'php8.3-*'
Note, selecting 'php8.3-dba' for glob 'php8.3-*'
Note, selecting 'php8.3-dev' for glob 'php8.3-*'
Note, selecting 'php8.3-dio' for glob 'php8.3-*'
Note, selecting 'php8.3-dom' for glob 'php8.3-*'
Note, selecting 'php8.3-ffi' for glob 'php8.3-*'
Note, selecting 'php8.3-fpm' for glob 'php8.3-*'
Note, selecting 'php8.3-ftp' for glob 'php8.3-*'
Note, selecting 'php8.3-gmp' for glob 'php8.3-*'
Note, selecting 'php8.3-stomp' for glob 'php8.3-*'
Note, selecting 'php8.3-posix' for glob 'php8.3-*'
Note, selecting 'php8.3-lz4' for glob 'php8.3-*'
Note, selecting 'php8.3-rdkafka' for glob 'php8.3-*'
Note, selecting 'php8.3-ldap' for glob 'php8.3-*'
Note, selecting 'php8.3-pdo' for glob 'php8.3-*'
Note, selecting 'php8.3-psr' for glob 'php8.3-*'
Note, selecting 'php8.3-ds' for glob 'php8.3-*'
Note, selecting 'php8.3-rrd' for glob 'php8.3-*'
Note, selecting 'php8.3-gd' for glob 'php8.3-*'
Note, selecting 'php8.3-pq' for glob 'php8.3-*'
Note, selecting 'php8.3-ps' for glob 'php8.3-*'
Note, selecting 'php8.3-xmlrpc' for glob 'php8.3-*'
Note, selecting 'php8.3-amqp' for glob 'php8.3-*'
Note, selecting 'php8.3-common' instead of 'php8.3-calendar'
Note, selecting 'php8.3-common' instead of 'php8.3-ctype'
Note, selecting 'php8.3-common' instead of 'php8.3-exif'
Note, selecting 'php8.3-common' instead of 'php8.3-ffi'
Note, selecting 'php8.3-common' instead of 'php8.3-fileinfo'
Note, selecting 'php8.3-common' instead of 'php8.3-ftp'
Note, selecting 'php8.3-common' instead of 'php8.3-gettext'
Note, selecting 'php8.3-common' instead of 'php8.3-iconv'
Note, selecting 'php8.3-common' instead of 'php8.3-pdo'
Note, selecting 'php8.3-common' instead of 'php8.3-phar'
Note, selecting 'php8.3-common' instead of 'php8.3-posix'
Note, selecting 'php8.3-common' instead of 'php8.3-shmop'
Note, selecting 'php8.3-common' instead of 'php8.3-sockets'
Note, selecting 'php8.3-common' instead of 'php8.3-sysvmsg'
Note, selecting 'php8.3-common' instead of 'php8.3-sysvsem'
Note, selecting 'php8.3-common' instead of 'php8.3-sysvshm'
Note, selecting 'php8.3-common' instead of 'php8.3-tokenizer'
Note, selecting 'php8.3-interbase' instead of 'php8.3-pdo-firebird'
Note, selecting 'php8.3-mysql' instead of 'php8.3-mysqli'
Note, selecting 'php8.3-mysql' instead of 'php8.3-mysqlnd'
Note, selecting 'php8.3-mysql' instead of 'php8.3-pdo-mysql'
Note, selecting 'php8.3-odbc' instead of 'php8.3-pdo-odbc'
Note, selecting 'php8.3-pgsql' instead of 'php8.3-pdo-pgsql'
Note, selecting 'php8.3-sqlite3' instead of 'php8.3-pdo-sqlite'
Note, selecting 'php8.3-sybase' instead of 'php8.3-pdo-dblib'
Note, selecting 'php8.3-xml' instead of 'php8.3-dom'
Note, selecting 'php8.3-xml' instead of 'php8.3-simplexml'
Note, selecting 'php8.3-xml' instead of 'php8.3-xmlreader'
Note, selecting 'php8.3-xml' instead of 'php8.3-xmlwriter'
php8.3-cli is already the newest version (8.3.10-1+ubuntu22.04.1+deb.sury.org+1).
php8.3-cli set to manually installed.
php8.3-common is already the newest version (8.3.10-1+ubuntu22.04.1+deb.sury.org+1).
php8.3-common set to manually installed.
php8.3-curl is already the newest version (8.3.10-1+ubuntu22.04.1+deb.sury.org+1).
php8.3-opcache is already the newest version (8.3.10-1+ubuntu22.04.1+deb.sury.org+1).
php8.3-opcache set to manually installed.
php8.3-readline is already the newest version (8.3.10-1+ubuntu22.04.1+deb.sury.org+1).
php8.3-readline set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php8.3-apcu : Conflicts: php-yac
 php8.3-gmagick : Conflicts: php-imagick
                  Recommends: ttf-dejavu-core but it is not installable
 php8.3-yac : Conflicts: php-apcu
E: Unable to correct problems, you have held broken packages.
alexandre@ubuntu:/var/www/SiteWebUniverseUtility$ 
`

**Comment by devnexen** [comment]
What I was trying to say is we do not maintain php packages nor pecl ones. You will have more luck reporting the issue [there](https://launchpad.net/ubuntuforums.org).

**Comment by aragon5956** [comment]
who responds on this site? is there a guarantee that someone will respond to me?

that is the question: https://answers.launchpad.net/ubuntuforums.org/+question/818553

**Comment by devnexen** [comment]
or you can eventually try [here](https://ubuntuforums.org/forumdisplay.php?f=333).

**Comment by aragon5956** [comment]
-_-"  ...  you do not answer the question : "who responds on this site?"

**Comment by devnexen** [comment]
Easy ... I said already here is _not for technical questions_ it is only related to php doc in french. If you ask in an ubuntu forum, stackoverflow, ...  you ll get an answer in a timely manner.
