### ISSUE TITLE
ftp_nlist can also return null 

### ISSUE THREAD

**Issue by lost-anjarrett** [php/doc-fr#171]
From manual page: https://php.net/function.ftp-nlist

---

It happened to me today, in v7.4.7 : 

```php
$list = ftp_nlist(null, '/');
var_dump($list);
```
will result in  
```
PHP Warning:  ftp_nlist() expects parameter 1 to be resource, null given in /var/www/ftp_nlist.php on line 2
NULL
```
I also confirmed this behavior in other php versions (5.3 and 7.2). 
Although it is understandable, the documentation does not mention it and I expected to have false as return

**Comment by Girgias** [comment]
You are providing an incorrect type to the function, the `null` return is documented https://www.php.net/manual/en/functions.internal.php and is applicable to a large range of functions.

This has nothing to do with ``ftp_nlist()``
