### ISSUE TITLE
sentance is contradictory

### ISSUE THREAD

**Issue by AlexisVS** [php/doc-fr#173]
From manual page: https://php.net/language.oop5.traits

---

Précédence[ ¶](https://www.php.net/manual/fr/language.oop5.traits.php#language.oop5.traits.precedence)

Une méthode héritée depuis une classe mère est écrasée par une méthode issue d'un Trait. L'ordre de précédence fait en sorte que les méthodes de la classe courante écrasent les méthodes issues d'un Trait, elles-mêmes surchargeant les méthodes héritées.

this sentance is contradictory

**Comment by adoy** [comment]
I'm not sure where the sentance is contradictory ? If the class inherits from a base class, the trait override the base class method, and if the current method define also the method, this method override the trait. I think the sentance is correcte even though it could be more clear. How would you write it to make it more clear ?

**Comment by devnexen** [comment]
Nothing wrong in this sentence in my view maybe I would not use 'ecrasee' here more maybe 'redefinie' or similar.

**Comment by adoy** [comment]
@Girgias I see in our doc multiple translations of "override"

"redéfinit" , "remplace", "écrase", "surcharge", ...

Should we add this to our `TRADUCTIONS.txt` ?

**Comment by Girgias** [comment]
It would make sense to add it to TRADUCTIONS.TXT but I think override might have different translations depending on the context. But consistency is best.
