### ISSUE TITLE
Typo in FRENCH documentation

### ISSUE THREAD

**Issue by Geompse** [php/doc-fr#186]
From manual page: https://php.net/function.mktime
---

Plural is missing "aux valeurs" (twice) // Le pluriel manque sur "au valeur" (deux fois)

L'année, peut être sur deux ou quatre chiffres, avec des valeurs allant de 0 à 69, correspondant au valeur 2000 à 2069 et 70 à 100, correspondant au valeur 1970 à 2000. Sur les systèmes où time_t un entier signé sur 32bits, ce qui est le plus courant de nos jours, la période valide pour year est quelque part près de 1901 et 2038.

L'année, peut être sur deux ou quatre chiffres, avec des valeurs allant de 0 à 69, correspondant aux valeurs 2000 à 2069 et 70 à 100, correspondant aux valeurs 1970 à 2000. Sur les systèmes où time_t un entier signé sur 32bits, ce qui est le plus courant de nos jours, la période valide pour year est quelque part près de 1901 et 2038.

**Comment by adoy** [comment]
Thanks for reporting this issue.
