### ISSUE TITLE
reference/pdo_sqlite/pdo-sqlite.xml

### ISSUE THREAD

**Issue by devnexen** [php/doc-fr#1953]
That s surely a little thing but [it s still reported here](https://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=1993c38d254743d8c0a2140ff6f797660997083d&f=reference/pdo_sqlite/pdo-sqlite.xml&c=on).

**Comment by devnexen** [comment]
@Fan2Shrek if you re up to it ... otherwise if you do not want I ll have a look later no worries :)

**Comment by Fan2Shrek** [comment]
This seems to be a forgotten part of commit f181c16b3308dc571209236676396163030f03f4 after c31f136659fd1d4f76f4e900a6b557f89a753761

#1954 :)

**Comment by devnexen** [comment]
Closed by [e5d6670](https://github.com/php/doc-fr/commit/e5d6670287baa715adeb4cbee6898027de4d2356)
