### ISSUE TITLE
FANN is not working on Wamp

### ISSUE THREAD

**Issue by Pitouflin** [php/doc-fr#247]
From manual page: https://php.net/fann.installation

---

After following the guide on https://www.php.net/manual/fr/fann.installation.php to use Fann on my wamp server (I use Windows, PHP 7.3.21 and the corresponding version of FANN and libfann) , Visual Studio Code doesn't detect FANN. I have an error telling my FANN-based functions are not defined but when I hover on them I have the description of what it is suppose to do.

Could somebody help me ?

**Comment by devnexen** [comment]
I would suggest to open an issue [here](https://github.com/bukka/php-fann) instead, this is definitely a more appropriate place.
