### ISSUE TITLE
Erreur de logique

### ISSUE THREAD

**Issue by MathiAs2Pique** [php/doc-fr#258]
From manual page: https://php.net/datetime.format

Il est marqué dans le tableau de référence:
`G | Heure, au format 24h, sans les zéros initiaux | 0 à 23`

Hors, c'est bien précisé "**sans** les zéros initiaux", tandis que l'exemple dis "**0** à 23".
Rien de bien grave, mais ça reste une erreur.

Bonne continuation

**Comment by Girgias** [comment]
Non, la documentation est correcte.
Les heures vont de 0 à 23. Si il y aurait un zéro initial ça serait `00:mm` et non ``0:mm`` (voir le format ``H``)
