### ISSUE TITLE
Translation issue en french on PCRE

### ISSUE THREAD

**Issue by jdelouche** [php/doc-fr#295]
From manual page: https://php.net/book.pcre

---
In french translation, should not be "rationnelles" but "régulières"
"rationnelles" -> 2/3
"régulières" -> /^.*$/

**Comment by pols12** [comment]
Why? OQLF recommends “rationnelle”:
https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/8359703/expression-rationnelle
