### ISSUE TITLE
On dit : il requiert/elle requiert

### ISSUE THREAD

**Issue by DagobertLeroy** [php/doc-fr#310]
https://www.php.net/manual/fr/language.types.type-juggling.php

On dit : il requiert/elle requiert
et pas : PHP ne requis pas

**Comment by devnexen** [comment]
Puis-je requérir un PR alors ? ;-)

**Comment by DagobertLeroy** [comment]
Bonsoir, David,

j'ai bien reçu ta réponse, datée 01/12/2022 14:19; je t'en remercie.

> Puis-je requérir un PR alors ? ;-)
Tu veux parler de Manu ?

Je suis, actuellement, sur https://www.jerome-turpin-peintre.net/?search-form

Bien festivement,
  
Dominique Braschi-Blondeau, 
 
« Il n’existe aujourd’hui qu’un péril au monde, du point de vue de la défense de notre société, et c’est que les travailleurs parviennent à se parler de leur condition et de leurs aspirations sans intermédiaires », Gianfranco Sanguinetti, Véridique rapport sur les dernières chances de sauver le capitalisme en Italie, 1976.

**Comment by devnexen** [comment]
Corrigé via [fa6a688](https://github.com/php/doc-fr/commit/fa6a68871fd3d10cfb49f8c6ff58bd5ee644dd96)
