### ISSUE TITLE
French Translation grammatical issue

### ISSUE THREAD

**Issue by frenchieRomainB** [php/doc-fr#351]
From manual page: https://php.net/mysqli.query

---
![image](https://user-images.githubusercontent.com/37306416/216602017-2c6c5974-ff48-4b48-ac95-dbad9ccb499f.png)

"les données doivent être correctement formatéES" i/o "les données doivent être correctement formaté"

**Comment by devnexen** [comment]
can you open a pull request please, since you found the issue ?
