### ISSUE TITLE
French translation repetition

### ISSUE THREAD

**Issue by Alecksee** [php/doc-fr#49]
From manual page: https://php.net/function.array-filter

---
The french translation for the "mode" parameter contain a repetition:
->  "Par défaut 0 par défaut qui passera la valeur comme seul argument de callback."
It could be:
-> "Par défaut 0 qui passera la valeur comme seul argument de callback."

**Comment by nikic** [comment]
I've enabled issues on doc-fr, so we can transfer translation issues there now :)
