### ISSUE TITLE
Small typo in the Oracle OCI8 module requirements

### ISSUE THREAD

**Issue by nlegaillart** [php/doc-fr#829]
Hi,

From manual page: https://php.net/oci8.requirements

I think there is a small typo in the Oracle OCI8 module requirements. In English we have:
```
In summary, Oracle Client 19, 18 and 12.2 can connect to Oracle Database 11.2 or greater.
```

while in French we have:
```
En résumé, Oracle Client 19, 18 et 12.2 peuvent se connecter à Oracle Database 10.2 ou supérieur.
```

so if the English documentation is right (I'm no Oracle specialist), we should have:
```
En résumé, Oracle Client 19, 18 et 12.2 peuvent se connecter à Oracle Database 11.2 ou supérieur.
```
I can open a PR to fix that if you wish.

Regards,

---
Nicolas

**Comment by devnexen** [comment]
Please do.

**Comment by nlegaillart** [comment]
Thanks, here it is: #830
