### ISSUE TITLE
Wrong translation of UTC format on `gmdate` function

### ISSUE THREAD

**Issue by llaville** [php/doc-fr#935]
The current version of `gmdate` function display a wrong format (corresponding to UTC)

See https://github.com/php/doc-fr/blob/master/reference/datetime/functions/gmdate.xml#L8

Expected :  "Formate une date/heure GMT/UTC" 
But got : "Formate une date/heure GMT/CUT"

**Comment by devnexen** [comment]
Feel free to open a PR :)

**Comment by llaville** [comment]
Everyone know the UTC keyword, but I don't think that french audience is agree with TUC.
Unless you want to said (Travail Utilité Collectif)

**Comment by Girgias** [comment]
Frankly the English is *also* wrong, `UTC` is the defacto abbreviation regardless of language. It being "non-sensical" is so that neither English nor French have the proper abbreviation. (something something diplomatic languages and lingua franca something something)

**Comment by llaville** [comment]
@Girgias Sorry but I disagree with you. If you consider UTC to be translate, so we must also translate GMT. And I'm 👎 for that point !
